---
output: pdf_document
params:
  fname: temp
  lname: temp
  address1: temp
  address2: temp
  donation: temp
  date: temp
---
`r params$date`  
\hfill\break
`r params$fname` `r params$lname`  
`r params$address1`  
`r params$address2`  
\hfill\break
**Subject: Thank You for Your Donation**  
\hfill\break
Dear `r params$fname`,  

The GWRFC Alumni Association wants to first take this time to thank you for your 
donation of $`r params$donation` as well as your support throughout the years. This
letter is intended to serve as contemporaneous written acknowledgment of your 
donation of $250 or more to comply with 26 U.S. Code ยง 170(f)(8)(a). The GWRFC 
Alumni Association has provided a jacket worth $200 to you. Consequently, the 
amount of your $`r params$donation` donation that is deductible for federal income 
tax purposes is limited to the excess of any money contributed over the value of 
goods provided by the GWRFC Alumni Association.  
\hfill\break
Best regards,  
  
Trevor Ceniviva  
President  
GWRFC Alumni Association
